### PR TITLE
Update dependencies, fix vulnerabilities

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
@brettritter-okta Any idea why the CI is failing for this PR? It seems like something might be misconfigured.

```
[ERROR] Please set the necessary Environment variables (ISSUER, CLIENT_ID, CLIENT_SECRET, USERNAME, PASSWORD)
```

**Comment by shuowu** [comment]
@mraible You probably need to create PR in this repo instead of from a fork repo to enable Travis CI.

**Comment by mraible** [comment]
@shuowu Unfortunately, I don't have permissions to do that.

**Comment by shuowu-okta** [comment]
PR moved to #90

**Pull request closed without merging**
